#!/bin/sh

CORDOVA_VERSION=$1
PLATFORM=$2
PLATFORM_VERSION=$3
ADDITIONAL_PLUGIN=$4

sh ./test/platform-add.sh $CORDOVA_VERSION $PLATFORM $PLATFORM_VERSION
sh ./test/plugin-add.sh $CORDOVA_VERSION $PLATFORM $PLATFORM_VERSION ..
sh ./test/platform-build.sh $CORDOVA_VERSION $PLATFORM $PLATFORM_VERSION
