#!/bin/bash
set -x #echo on
set -e #exit on error

CORDOVA_VERSION=$1
PLATFORM=$2
PLATFORM_VERSION=$3
ADDITIONAL_PLUGIN=$4

npm install

sh ./test/platform-add.sh $CORDOVA_VERSION $PLATFORM $PLATFORM_VERSION
sh ./test/plugin-add.sh $CORDOVA_VERSION $PLATFORM $PLATFORM_VERSION ..
sh ./test/plugin-add.sh $CORDOVA_VERSION $PLATFORM $PLATFORM_VERSION $ADDITIONAL_PLUGIN
sh ./test/platform-build.sh $CORDOVA_VERSION $PLATFORM $PLATFORM_VERSION
